rodada = 0 
draw_set_font(Font1)
escolha = 0;
vidas = 1;
p0 = instance_create_layer(0,0,"Instances", ObjectPergunta);
p0.pergunta ="BEM VIDO AO SHOW DO CONVENTO\nESCOLHA SUA DIFICULDADE";
p0.resposta1 = "FACIL";
p0.resposta2 = "MEDIO";
p0.resposta3 = "DIFICIL";
p0.resposta4 = "VER PLACAR(TODO)";
p0.respostaCerta = 1;
p1 = instance_create_layer(0,0,"Instances", ObjectPergunta);
p1.pergunta ="PERGUNTA1ÉÉÉÉÉ";
p1.resposta1 = "RESPOSTA1CERTA";
p1.resposta2 = "RESPOSTA2";
p1.resposta3 = "RESPOSTA3";
p1.resposta4 = "RESPOSTA4";
p1.respostaCerta = 1;
p2 = instance_create_layer(0,0,"Instances", ObjectPergunta);
p2.pergunta ="PERGUNTA2";
p2.resposta1 = "RESPOSTA1";
p2.resposta2 = "RESPOSTA2CERTA";
p2.resposta3 = "RESPOSTA3";
p2.resposta4 = "RESPOSTA4";
p2.respostaCerta = 2;
p3 = instance_create_layer(0,0,"Instances", ObjectPergunta);
p3.pergunta ="PERGUNTA3";
p3.resposta1 = "RESPOSTA1";
p3.resposta2 = "RESPOSTA2";
p3.resposta3 = "RESPOSTA3CERTA";
p3.resposta4 = "RESPOSTA4";
p3.respostaCerta = 3;
perguntas = [p0, p1, p2, p3]
perguntas = array_shuffle(perguntas);
pontos = 1;
