rodada = 0 
perguntas = ["BEM VINDO AO SHOW DO CONVENTO", "SEGUNDA PERGUNTA", "ACERTOU"]
respotas1 = ["FACIL", "RESPOSTA1 PERGUNTA2", "BLALALALA"]
respotas2 = ["MEDIO", "RESPOSTA2 PERGUNTA2", "BLALALA"]
respotas3 = ["DIFICIL", "RESPOSTA3 CERTA PERGUNTA2", "BLALALA"]
respotas4 = ["VER PLACAR", "RESPOSTA4 PERGUNTA2", "BLALALA"]
respostacerta = [5, 3, 4]
escolha = 0;
vidas = 1;
pontos = 0;